services:
  atk-main-bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    container_name: atk-main-bot
    restart: unless-stopped
    
    # Mount volumes to persist data
    volumes:
      - ./bot_data:/app/bot_data
      - ./bot_screenshots:/app/bot_screenshots
    
    # Environment variables (optional customization)
    environment:
      - PYTHONUNBUFFERED=1
      - HEADLESS=true
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  bf-bot-int7:
    build:
      context: .
      dockerfile: ./bot_battlefield/Dockerfile
    container_name: bf-bot-int7
    restart: unless-stopped
    
    # Environment variables (optional customization)
    environment:
      - PYTHONUNBUFFERED=1
      - HEADLESS=true
      - KF_IS_INT_SERVER=true

  bf-bot-de15:
    build:
      context: .
      dockerfile: ./bot_battlefield/Dockerfile
    container_name: bf-bot-de15
    restart: unless-stopped
    
    # Environment variables (optional customization)
    environment:
      - PYTHONUNBUFFERED=1
      - HEADLESS=true
      - KF_IS_INT_SERVER=false